# MongoDB connection settings
mongodb:
  connection-string: "mongodb://localhost:27017"

# Treasure hunt gameplay settings
treasure:
  max-clue-distance: 100.0       # Maximum distance a clue can be from its treasure
  clue-difficulty: "medium"      # Default clue difficulty (easy, medium, hard)
  min-clues-required: 1          # Minimum clues required to find a treasure
  clue-find-radius: 3.0          # Radius for detecting clues
  find-radius: 2.0               # Radius for detecting treasures
  max-treasures-per-hunt: 5      # Maximum treasures a player can hunt at once

# Reward items by rarity level (example placeholder)
rewards:
  1:
    - type: DIAMOND
      amount: 1
  2:
    - type: EMERALD
      amount: 2
  3:
    - type: NETHERITE_INGOT
      amount: 1

# Messages for commands, listeners, and game events
messages:
  plugin-enabled: "&aTreasureHunt plugin enabled!"
  plugin-disabled: "&cTreasureHunt plugin disabled!"
  player-only: "&cThis command can only be used by players!"
  no-permission: "&cYou do not have permission to use this command!"
  error: "&cError: %s"

  # Clue command messages
  usage-clue-error: "&cUsage: /clue <create|delete|list|solve> <treasure> [description]"
  usage-clue-create: "&cUsage: /clue create <treasure> <description>"
  usage-clue-delete-error: "&cUsage: /clue delete <treasure>"
  usage-clue-list: "&cUsage: /clue list <treasure>"
  usage-clue-solve: "&cUsage: /clue solve <treasure> <description>"
  clue-created: "&aClue created for treasure %s!"
  clue-invalid: "&cInvalid treasure %s or clue creation failed!"
  clues-deleted: "&aAll clues deleted for treasure %s!"
  clue-list: "&aClues for treasure %s:"
  no-clues: "&cNo clues found for treasure %s!"
  clue-solved: "&aClue solved for treasure %s!"
  clue-not-found: "&cClue not found for treasure %s!"
  invalid-clue-command: "&cInvalid clue command!"
  clue-solved-auto: "&aYou found a clue for treasure %s!"

  # Hunt command messages
  usage-hunt-error: "&cUsage: /hunt <start|competition|leaderboard|progress>"
  usage-hunt-competition: "&cUsage: /hunt competition start"
  invalid-hunt-command: "&cInvalid hunt command!"
  hunt-started: "&aHunt started with %d treasures!"
  no-treasures-available: "&cNo treasures available to hunt!"
  competition-started: "&aTreasure hunt competition started!"
  team-list: "&aTeam Leaderboard:"
  no-teams: "&cNo teams found!"
  progress-header: "&aYour Hunt Progress:"
  cooldown-active: "&cPlease wait before starting another hunt!"

  # Team command messages
  usage-team-error: "&cUsage: /team <create|invite|kick|list>"
  usage-team-create: "&cUsage: /team create <name>"
  usage-team-invite: "&cUsage: /team invite <player>"
  usage-team-kick: "&cUsage: /team kick <player>"
  invalid-team-command: "&cInvalid team command!"
  team-created: "&aTeam %s created!"
  team-exists: "&cTeam %s already exists!"
  team-not-found: "&cYou are not in a team!"
  team-invited: "&aInvited %s to your team!"
  team-invite-received: "&aYou have been invited to a team!"
  team-invite-failed: "&cFailed to invite %s to the team!"
  team-kicked: "&aKicked %s from your team!"
  team-kick-received: "&cYou have been kicked from the team!"
  team-kick-failed: "&cFailed to kick %s from the team!"
  player-not-found: "&cPlayer %s not found!"

  # Treasure command messages
  usage-treasure-error: "&cUsage: /treasure <create|delete|list>"
  usage-treasure-create: "&cUsage: /treasure create <name> <rarity>"
  usage-treasure-delete: "&cUsage: /treasure delete <name>"
  invalid-treasure-command: "&cInvalid treasure command!"
  treasure-created: "&aTreasure %s created with rarity %r!"
  treasure-exists: "&cTreasure %s already exists!"
  treasure-deleted: "&aTreasure %s deleted!"
  treasure-not-found: "&cTreasure %s not found!"
  treasure-list: "&aAvailable Treasures:"
  no-treasures: "&cNo treasures found!"
  invalid-rarity: "&cRarity must be a positive integer!"
  invalid-rarity-format: "&cRarity must be a valid number!"

  # Listener messages
  treasure-found: "&aYou found treasure %s!"
  no-clue-solved: "&cYou need to solve at least %d clue(s) first!"
  reward-received: "&aReceived reward: %s!"
  protected-region: "&cThis area is protected and cannot be interacted with!"