# Treasure Hunt Plugin Configuration
mongodb:
  connection-string: "mongodb://localhost:27017"
treasure:
  max-clue-distance: 100.0 # Maximum distance between clue and treasure
  clue-difficulty: medium # Options: easy, medium, hard
  default-rarity: 3
  min-clues-required: 1 # Minimum clues to solve before finding a treasure
  find-radius: 2.0 # Maximum distance in blocks for treasure hunting
  clue-find-radius: 3.0 # Radius for detecting clue auto-detection
  max-treasures-per-hunt-per: 5
messages:
  player-only: "&cOnly players can use this command!"
  no-permission: "&cYou don't have permission to use this command!"
  error: "&cAn error occurred: %s"
  usage-treasure-error: "&eUsage: /treasure <create|delete|list>"
  invalid-treasure-command: "&cInvalid subcommand! Use create, delete, or list."
  usage-treasure-create: "&eUsage: /treasure create <name> <rarity>"
  invalid-rarity: "&cRarity must be a positive integer!"
  invalid-rarity-format: "&cRarity must be a number!"
  treasure-created: "&aTreasure '&6%s&a' created with rarity %r!"
  treasure-exists: "&cTreasure '&6%s&c' already exists!"
  usage-treasure-delete: "&eUsage: /treasure delete <name>"
  treasure-deleted: "&aTreasure '&6%s&a' deleted!"
  treasure-not-found: "&cTreasure '&6%s&c' not found!"
  no-treasures: "&eNo treasures available!"
  treasure-list: "&aAvailable treasures:"
  usage-clue-error: "&eUsage: /clue <create|delete|list|solve> <treasure>"
  invalid-clue-command: "&cInvalid subcommand! Use create, delete, list, or solve."
  usage-clue-create: "&eUsage: /clue create <treasure> <description>"
  clue-created: "&aClue created for treasure '&6%s&a'!"
  clue-invalid: "&cTreasure '&6%s&c' not found or clue too far!"
  usage-clue-delete-error: "&eUsage: /clue delete <treasure>"
  clues-deleted: "&aClues deleted for treasure '&6%s&a'!"
  usage-clue-list: "&eUsage: /clue list <treasure>"
  no-clues: "&eNo clues available for '&6%s&e'!"
  clue-list: "&aClues for '&6%s&a':"
  usage-clue-solve: "&eUsage: /clue solve <treasure> <description>"
  clue-solved: "&aClue solved for treasure '&6%s&a'!"
  clue-not-found: "&cTreasure or clue not found for '&6%s&c'!"
  usage-team-error: "&eUsage: /team <create|invite|kick|list>"
  invalid-team-command: "&cInvalid subcommand! Use create, invite, kick, or list."
  usage-team-create: "&eUsage: /team create <name>"
  team-created: "&aTeam '&2%s&a' created!"
  team-exists: "&cTeam '&2%s&c' already exists!"
  usage-team-invite: "&eUsage: /team invite <player>"
  player-not-found: "&cPlayer '&c%s&c' not found!"
  team-invited: "&aInvited &c%s&a to your team!"
  team-invite-received: "&aYou have been invited to a team!"
  team-not-found: "&cYou are not in a team!"
  team-invite-failed: "&cFailed to invite &c%s&c to your team!"
  usage-team-kick: "&eUsage: /team kick <player>"
  team-kicked: "&aKicked &c%s&a from your team!"
  team-kick-received: "&cYou have been kicked from the team!"
  team-kick-failed: "&cFailed to kick &c%s&c from your team!"
  no-teams: "&eNo teams available!"
  team-list: "&aTeams:"
  usage-hunt-error: "&eUsage: /hunt <start|competition>"
  invalid-hunt-command: "&cInvalid subcommand! Use start or competition."
  hunt-started: "&aHunt started! Clue: "
  all-treasures-found: "&eYou've found all treasures!"
  usage-hunt-competition: "&eUsage: /hunt competition start"
  competition-start: "&a&lTreasure hunt competition has started!"
  competition-end: "&a&lCompetition ended! Winner: &2%s"
  treasure-found: "&a&lTreasure '&6%s&a&l' found!"
  clue-solved-location: "&aClue for treasure '&6%s&a' solved by reaching its location!"
  not-enough-clues: "&cYou must solve at least %s clue(s) first!"
  plugin-enabled: "&aTreasureHunt plugin enabled!"
  plugin-disabled: "&cTreasureHunt plugin disabled!"