name: TreasureHunt
version: 1.0.0
main: gg.kite.TreasureHunt
api-version: 1.21
description: A Minecraft plugin for treasure hunting with clues, teams, and competitions.
author: KiteGG
depend: []
softdepend: [WorldGuard]

commands:
  treasure:
    description: Manage treasures in the TreasureHunt plugin.
    usage: /<command> <create|delete|list> [args]
    permission: treasurehunt.treasure
  clue:
    description: Manage clues for treasures.
    usage: /<command> <create|delete|list|solve> <treasure> [description]
    permission: treasurehunt.clue
  team:
    description: Manage teams for treasure hunts.
    usage: /<command> <create|invite|kick|list> [args]
    permission: treasurehunt.team
  hunt:
    description: Start or manage treasure hunts and competitions.
    usage: /<command> <start|competition|leaderboard|progress> [args]
    permission: treasurehunt.hunt

permissions:
  treasurehunt.treasure:
    description: Allows managing treasures.
    default: op
  treasurehunt.clue:
    description: Allows managing clues.
    default: op
  treasurehunt.team:
    description: Allows managing teams.
    default: true
  treasurehunt.hunt:
    description: Allows starting hunts and viewing progress.
    default: true
  treasurehunt.admin:
    description: Allows starting competitions and advanced administration.
    default: op